blog/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDeleteView, PostListView, PostDetailView, my_draft, my_post, \
    add_comment

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),

    path('contact', views.contact_form, name="contact"),

    path('post/create/', PostCreateView.as_view(), name='post_form'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/', PostListView.as_view(), name='post_list'),
    path('post_by_<str:user>/', PostListView.as_view(), name='user_post_list'),

    path('my_post', my_post, name='user_my_post_list'),
    path('my_draft/', my_draft,  name='user_draft_post_list'),

    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/comment/', add_comment, name='add_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from blog.views import RegisterFormView, login_request, logout_request, UpdateProfile, UserProfile, PublicProfile
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/blog/post/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('accounts/login/', login_request, name='login'),
    path('accounts/update_profile/', UpdateProfile.as_view(), name='update_profile'),

    path('accounts/', UserProfile.as_view(), name='profile'),
    path('accounts/<int:pk>/', PublicProfile.as_view(), name='user_profile'),

    path('logout', logout_request, name="logout"),


]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse


class Post(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_draft = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular post instance."""
        return reverse('blog:post_detail', args=[str(self.id)])


class Comment(models.Model):
    name = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_reviewed = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Comment

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'message')


class ContactFrom(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email:
            raise forms.ValidationError("Email can't be empty")
        return email

    def clean_subject(self):
        subject = self.cleaned_data['subject']
        if not subject:
            raise forms.ValidationError("Subject can't be empty")
        return subject

    def clean_message(self):
        message = self.cleaned_data['message']
        if not message:
            raise forms.ValidationError("Message can't be empty")
        return message

blog/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import authenticate, login, logout, get_user_model
from .forms import RegisterForm, CommentForm, ContactFrom
from .models import Post
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.template.loader import render_to_string

User = get_user_model()


def index(request):
    return render(request, 'index.html')


class RegisterFormView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy("blog:post_list")

    def form_valid(self, form):
        user = form.save()
        user = authenticate(username=user.username, password=form.cleaned_data.get("password1"))
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("blog:post_list")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="registration/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("blog:post_list")


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'registration/update_profile.html'
    success_url = reverse_lazy('blog:post_list')
    success_message = 'Profile updated'

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class UserProfile(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'registration/profile.html'

    def get_object(self, queryset=None):
        return self.request.user


class PublicProfile(generic.DetailView):
    model = User
    template_name = 'registration/public_profile.html'

    def get_object(self, queryset=None):
        user = User.objects.get(pk=self.kwargs['pk'])
        return user

    # signal(send mail to admin)


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    fields = ['title', 'short_description', 'text', 'image', 'is_draft', ]
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    fields = ['title', 'short_description', 'text', 'image', 'is_draft']
    success_url = reverse_lazy('blog:post_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        return queryset


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        return queryset


class PostListView(generic.ListView):
    model = Post
    paginate_by = 29

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('author').annotate(
            comment_count=Count('comments', filter=Q(comments__is_reviewed=True))).all()
        queryset = queryset.order_by('-created_at')
        username = self.kwargs.get('user')
        if username:
            queryset = queryset.filter(author__username=username)
        return queryset


class PostDetailView(generic.DetailView):
    model = Post
    queryset = Post.objects.select_related('author').all()
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(num_posts=Count('author__post'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = self.object.comments.filter(is_reviewed=True)
        paginator = Paginator(comments, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['comments'] = page_obj
        return context


# signal(send mail to admin)
def add_comment(request, pk):
    post = Post.objects.get(pk=pk)
    comments = post.comments.all()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form})


@login_required
def my_draft(request):
    drafts = Post.objects.filter(author=request.user, is_draft=True)
    paginator = Paginator(drafts, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/user_draft_post_list.html',
                  {'page_obj': page_obj, 'is_paginated': page_obj.has_other_pages()})


@login_required
def my_post(request):
    post_list = Post.objects.filter(author=request.user, is_draft=False)
    queryset = post_list.annotate(comment_count=Count('comments', filter=Q(comments__is_reviewed=True)))
    paginator = Paginator(queryset, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/user_my_post_list.html',
                  {'page_obj': page_obj, 'is_paginated': page_obj.has_other_pages()})


def contact_form(request):
    data = dict()
    if request.method == "POST":
        form = ContactFrom(request.POST)
        if form.is_valid():
            # email = form.cleaned_data['email']
            # subject = form.cleaned_data['subject']
            # message = form.cleaned_data['message']
            # # contact_send_mail.delay(subject, message, email)
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = ContactFrom()
    data['html_form'] = render_to_string('blog/contact.html', {'form': form}, request=request)
    return JsonResponse(data)

templates/blog/contact.html
{% load widget_tweaks %}

<form method="post" action="{% url 'blog:contact' %}" class="js-contact-form needs-validation">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Contact us</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {% for field in form %}
            <div class="mb-3{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="col-form-label">{{ field.label }}</label>
                {% render_field field class+="form-control" %}
                {% if form.is_bound %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback valid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Send message</button>
    </div>
</form>

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Post{% endblock %}

{% block content %}

    <div class="container text-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <p>Are you sure you want to delete '{{ object.title }}'?</p>
                {{ form }}
            </div>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
    </div>

{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

    <div class="container">
        <div class="card shadow-sm">
            {% if object.image and object.image.url %}
                <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ object.image.url }}"
                     role="img" aria-label="Placeholder: Thumbnail">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"></rect>
            {% endif %}
            <div class="card-body">
                <h3 class="mb-0">{{ object.title }}</h3>
                <p class="card-text">{{ object.text }}</p>
                <div class="mb-1 text-body-secondary">{{ object.created_at }}</div>
                <div class="d-flex justify-content-between align-items-center">
                    {% if object.author == request.user %}
                        <div class="btn-group">
                            <button type="button"
                                    class="btn btn-warning btn-sm js-update-book"
                                    onclick='location.href="{% url 'blog:post_update' object.pk %}"'>
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button"
                                    class="btn btn-danger btn-sm js-delete-book"
                                    onclick='location.href="{% url 'blog:post_delete' object.pk %}"'>
                                <span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </div>
                    {% endif %}
                    <small class="text-body-secondary">{{ object.num_posts }} posts by <a
                            href="{% url 'user_profile' post.author.pk %}">
                        {{ object.author }}</a></small>
                </div>
            </div>
        </div>
        <h3 class="text-center m-2">Add a Comment</h3>
        <form method="post" action="{% url 'blog:add_comment' object.pk %}" class="needs-validation" novalidate>
            {% csrf_token %}
            {% if user.is_authenticated %}
                <input type="hidden" name="name" id="name" value="{{ user.username }}" readonly>
            {% else %}
                <div class="mb-3">
                    <label class="form-label" for="name">Name:</label>
                    <input class="form-control" type="text" name="name" id="name" required>
                    <div class="invalid-feedback">
                        Please provide a name.
                    </div>
                </div>
            {% endif %}
            <div class="mb-3">
                <label class="form-label" for="message">Message:</label>
                <textarea class="form-control" name="message" id="message" required></textarea>
                <div class="invalid-feedback">
                    Please provide a message.
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        <h3 class="text-center m-2">Comments</h3>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if comments %}
                {% for comment in comments %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-text">{{ comment.name }}</h5>
                                <p class="card-text">{{ comment.message }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-body-secondary">{{ comment.created_at }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No comments yet.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}
    <div class="container p-5">
        <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
                <label for="{{ form.title.id_for_label }}" class="form-label">Title: </label>
                <input name="{{ form.title.name }}" type="text" class="form-control" id="{{ form.title.id_for_label }}"
                       required value="{{ object.title }}">
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class="mb-3">
                <label for="{{ form.short_description.id_for_label }}" class="form-label">Short Description: </label>
                <input name="{{ form.short_description.name }}" type="text" class="form-control"
                       id="{{ form.short_description.id_for_label }}" required value="{{ object.short_description }}">
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class="mb-3">
                <label for="{{ form.text.id_for_label }}" class="form-label">Text: </label>
                <textarea name="{{ form.text.name }}" class="form-control" id="{{ form.text.id_for_label }}"
                          required>{{ object.text }}</textarea>
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class="mb-3">
                <label for="{{ form.image.id_for_label }}">Image:</label>
                {% if object.image %}
                    Currently: <a href="{{ object.image.url }}">{{ object.image.name }}</a>
                    <input type="checkbox" name="image-clear" id="image-clear_id">
                    <label for="image-clear_id">Clear</label><br>
                {% endif %}
                Change:
                <input type="file" name="{{ form.image.name }}" accept="image/*" id="{{ form.image.id_for_label }}">
                                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class="mb-3 form-check">
                <input name="{{ form.is_draft.name }}" type="checkbox" class="form-check-input"
                       id="{{ form.is_draft.id_for_label }}">
                <label class="form-check-label" for="{{ form.is_draft.id_for_label }}">Is Draft: </label>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}

    <div class="album py-5">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for post in object_list %}
                    {% if not post.is_draft %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <h3 class="mb-0"><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
                                    <p class="card-text">{{ post.short_description }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-outline-secondary" onclick='location.href="{% url 'user_profile' post.author.pk %}"'>{{ post.author }}</button>
                                        </div>
                                        <small class="text-body-secondary">{{ post.comment_count }} comments</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <h3 class="mb-0">No posts yet</h3>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/user_draft_post_list.html
{% extends 'base.html' %}

{% block title %}
    My drafts
{% endblock %}

{% block content %}

    <div class="album py-5">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for post in page_obj %}
                    {% if post.is_draft %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <h3 class="mb-0"><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
                                    <p class="card-text">{{ post.short_description }}</p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <h3 class="mb-0">No posts yet</h3>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/user_my_post_list.html
{% extends 'base.html' %}

{% block title %}
    My posts
{% endblock %}

{% block content %}

    <div class="album py-5">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for post in page_obj %}
                    {% if not post.is_draft %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <h3 class="mb-0"><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
                                    <p class="card-text">{{ post.short_description }}</p>
                                    <small class="text-body-secondary">{{ post.comment_count }} comments</small>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <h3 class="mb-0">No posts yet</h3>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/user_post_list.html
{% extends 'base.html' %}

{% block title %}
    {{ object.username }}
{% endblock %}

{% block content %}
    <h2>Post by: {{ object.username }}</h2>
    <ul>
    {% for post in object.post_set.all%}
        <li>
            <p><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></p>
            <p>{{ post.short_description }}</p>
        </li>
    {% empty %}
        <li>No posts yet</li>
    {% endfor %}
    </ul>
{% endblock %}