blog/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDeleteView, PostListView, PostDetailView, my_draft, my_post, \
    add_comment

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),

    path('contact', views.contact_form, name="contact"),

    path('post/create/', PostCreateView.as_view(), name='post_form'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/', PostListView.as_view(), name='post_list'),
    path('post_by_<str:user>/', PostListView.as_view(), name='user_post_list'),

    path('my_post', my_post, name='user_my_post_list'),
    path('my_draft/', my_draft,  name='user_draft_post_list'),

    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/comment/', add_comment, name='add_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from blog.views import RegisterFormView, login_request, logout_request, UpdateProfile, UserProfile, PublicProfile
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/blog/post/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('accounts/login/', login_request, name='login'),
    path('accounts/update_profile/', UpdateProfile.as_view(), name='update_profile'),

    path('accounts/', UserProfile.as_view(), name='profile'),
    path('accounts/<int:pk>/', PublicProfile.as_view(), name='user_profile'),

    path('logout', logout_request, name="logout"),


]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
{% if messages %}
    <div class="row text-center">
        <div class="col-sm-12">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
                        {{ message.tags|title }}{% endif %}!</strong> {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom"
            id="blog-header">
        {% if request.user.is_authenticated %}
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <span class="fs-4">Welcome, {{ request.user.get_username }}</span>
                </a>
            </div>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:post_list' %}" class="nav-link px-2 link-secondary">Home</a></li>
                <li><a href="{% url 'blog:post_form' %}" class="nav-link px-2">Create post</a></li>
                <button type="button" class="nav-link px-2 js-contact" data-url="{% url 'blog:contact' %}">Contact us
                </button>
                <li class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">Profile</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'profile' %}" class="dropdown-item">My profile</a></li>
                        <li><a href="{% url 'blog:user_my_post_list' %}" class="dropdown-item">My post</a>
                        </li>
                        <li><a href="{% url 'blog:user_draft_post_list' %}" class="dropdown-item">My
                            draft</a></li>
                        {% if user.is_staff %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a href="{% url 'admin:index' %}" class="dropdown-item">Admin</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <div class="col-md-3 text-end">
                <button type="button" class="btn btn-outline-primary me-2"
                        onclick='location.href="{% url 'logout' %}?next={{ request.path }}"'>Logout
                </button>
            </div>

        {% else %}

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:post_list' %}" class="nav-link px-2 link-secondary">Home</a></li>
                <button type="button" class="nav-link px-2 js-contact" data-url="{% url 'blog:contact' %}">Contact us
                </button>
            </ul>

            <div class="col-md-3 text-end">
                <button type="button" class="btn btn-outline-primary me-2"
                        onclick='location.href="{% url 'login' %}?next={{ request.path }}"'>Login
                </button>
                <button type="button" class="btn btn-primary"
                        onclick='location.href="{% url 'register' %}?next={{ request.path }}"'>Register
                </button>
            </div>
        {% endif %}
    </header>
</div>

<main>
    {% block content %}

    {% endblock %}
    {% block pagination %}
        {% if is_paginated %}
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}

                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page=1">First</a>
                </li>

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                            <a class="page-link">{{ num }} <span class="sr-only"></span></a>
                        </li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a class="page-link" href="{{ request.path }}?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
        {% if comments.has_other_pages %}
            <ul class="pagination justify-content-center mt-5">
                {% if comments.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}
                {% if comments.number > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First</a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="#">Page {{ comments.number }} of {{ comments.paginator.num_pages }}.</a>
                </li>
                {% if comments.number < comments.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ comments.next_page_number }}">Next</a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.paginator.num_pages }}">Last</a>
                </li>

            </ul>
        {% endif %}
    {% endblock %}
    <div class="modal fade" id="modal-blog">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
</main>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>
        <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-body-secondary" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#twitter"></use>
            </svg>
        </a></li>
        <li class="ms-3"><a class="text-body-secondary" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#instagram"></use>
            </svg>
        </a></li>
        <li class="ms-3"><a class="text-body-secondary" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#facebook"></use>
            </svg>
        </a></li>
    </ul>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous">
</script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8="
        crossorigin="anonymous">
</script>
<script src="{% static 'js/blog.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Main{% endblock %}

{% block content %}

{% endblock %}